### ISSUE TITLE
Illegal instruction on Mac Catalina

### ISSUE THREAD

**Issue by loopxia** [Conflux-Chain/conflux-docker#8]
System:
Mac catalina
version: 10.15.7

Error:
$ docker run -p 12537:12537 --name cfx-node confluxchain/conflux-rust
CFXDOCKER: config file set success !
./conflux.sh: line 8:    26 Illegal instruction     ./conflux --config ./default.toml
^C^C^C^C(node:13) UnhandledPromiseRejectionWarning: Error: connect ECONNREFUSED 127.0.0.1:12537
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1146:16)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:13) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:13) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
./start.sh: line 8: fg: job has terminated

**Comment by zakicheung** [comment]
I had the same problem on OS 10.15, then it woking ok on OS 10.16
